local spell_priority = {
    "flame_shield",
    "ice_blade",
    "inferno",
    "hydra",
    "ball",
    "frost_bolt",
	"teleport_ench",
    "teleport",
    "unstable_current",
    "familiars",
    "ice_shards",
    "frozen_orb",
    "chain_lightning",
    "blizzard",
    "firewall",
    "meteor",
    "charged_bolts",
    "arc_lash",
    "incinerate",
    "frost_nova",
    "fire_bolt",
    "spark",
    "ice_armor",
    "fireball",
	"spear",
}

return spell_priority 